#!/bin/sh

# reconfigure.sh — Read config model, diff against running state, start/stop as needed
# Called by configd: configctl proxygateway reconfigure

SCRIPT_DIR=$(dirname "$0")
RUNDIR="/var/run/proxygateway"

mkdir -p "$RUNDIR"

# Read desired state from the model via configd template or direct XML parse
# The PHP controller writes a JSON config to a known location before calling reconfigure
DESIRED_CONFIG="/var/run/proxygateway/desired.json"

if [ ! -f "$DESIRED_CONFIG" ]; then
    echo "No desired configuration found at $DESIRED_CONFIG"
    echo "This file is generated by the API controller before reconfigure is called."
    exit 0
fi

# Get list of currently running connections
RUNNING=""
for conf in "${RUNDIR}"/*.conf; do
    [ -f "$conf" ] || continue
    conn_name=$(basename "$conf" .conf)
    RUNNING="$RUNNING $conn_name"
done

# Parse desired config and start/stop connections
# Expected JSON format: {"connections": [{"name": "x", "enabled": true, ...}, ...]}
# Use a simple Python script to handle JSON parsing and diff logic
/usr/local/bin/python3 "${SCRIPT_DIR}/reconfigure.py" "$DESIRED_CONFIG"
