#!/bin/sh

# reconfigure.sh — Read config model, diff against running state, start/stop as needed
# Called by configd: configctl proxygateway reconfigure
# Output is captured by configd (type:script_output) and returned to the API.
#
# Concurrency: configd serializes commands of the same action type, so
# concurrent reconfigure runs are already prevented at the configd level.

SCRIPT_DIR=$(dirname "$0")
RUNDIR="/var/run/proxygateway"
LOGDIR="/var/log/proxygateway"
RECONFIGURE_LOG="${LOGDIR}/reconfigure.log"

# Source structured logging library
. "${SCRIPT_DIR}/lib/logging.sh"

log_init "reconfig" "-" "info"

mkdir -p -m 0750 "$RUNDIR"
mkdir -p "$LOGDIR"

# Read desired state from the model via configd template or direct XML parse
# The PHP controller writes a JSON config to a known location before calling reconfigure
DESIRED_CONFIG="/var/run/proxygateway/desired.json"

if [ ! -f "$DESIRED_CONFIG" ]; then
    log_warning "No desired configuration found at $DESIRED_CONFIG"
    log_info "This file is generated by the API controller before reconfigure is called"
    exit 0
fi

# Run reconfigure.py and capture output to both stdout and a persistent log file.
# stdout goes back to configd (type:script_output) -> API -> Apply dialog.
# Log file persists for the diagnostics page to display.
# NOTE: reconfigure.py logs only to stdout; we tee it to the log file here.
# Do NOT add a Python FileHandler — that would double every line.
echo "=== Reconfigure started at $(date) ===" > "$RECONFIGURE_LOG"

# Use a temp file to capture exit code since PIPESTATUS is bash-only
EXIT_FILE=$(mktemp /tmp/pgw_rc.XXXXXX)
( /usr/local/bin/python3 "${SCRIPT_DIR}/reconfigure.py" "$DESIRED_CONFIG" 2>&1; echo $? > "$EXIT_FILE" ) | tee -a "$RECONFIGURE_LOG"
EXIT_CODE=$(cat "$EXIT_FILE")
rm -f "$EXIT_FILE"

echo "=== Reconfigure finished at $(date) (exit code: ${EXIT_CODE}) ===" >> "$RECONFIGURE_LOG"
exit "${EXIT_CODE:-1}"
