[start]
command:/usr/local/etc/rc.d/opnsense-proxygateway start
parameters:%s
type:script
message:start proxy gateway instance %s

[stop]
command:/usr/local/etc/rc.d/opnsense-proxygateway stop
parameters:%s
type:script
message:stop proxy gateway instance %s

[restart]
command:/usr/local/etc/rc.d/opnsense-proxygateway restart
parameters:%s
type:script
message:restart proxy gateway instance %s
description:Restart Proxy Gateway

[status]
command:/usr/local/opnsense/scripts/OPNsense/ProxyGateway/status.py
parameters:
type:script_output
message:show proxy gateway status

[setup]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/ProxyGateway/setup.sh
parameters:%s
type:script
message:setup proxy gateway connection %s

[teardown]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/ProxyGateway/teardown.sh
parameters:%s
type:script
message:teardown proxy gateway connection %s

[reconfigure]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/ProxyGateway/reconfigure.sh
type:script_output
message:reconfigure proxy gateway connections

[healthcheck]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/ProxyGateway/healthcheck.sh
parameters:%s
type:script_output
message:health check proxy gateway %s

[watchdog]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/ProxyGateway/watchdog.sh
type:script_output
message:proxy gateway watchdog check

[clearlogs]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/ProxyGateway/clear_logs.sh
parameters:%s
type:script_output
message:clear proxy gateway logs %s

[speedtest]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/ProxyGateway/speedtest.sh
parameters:%s
type:script_output
message:speed test proxy gateway %s

[speedtestcron]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/ProxyGateway/speedtest_cron.sh
type:script_output
message:proxy gateway speed test cron

[forcedown]
command:/usr/local/bin/php /usr/local/opnsense/scripts/OPNsense/ProxyGateway/gateway_force_down.php
parameters:%s
type:script_output
message:force down/up proxy gateway %s
