[start]
command:/usr/local/etc/rc.d/proxygateway start
type:script
message:Starting Proxy Gateway

[stop]
command:/usr/local/etc/rc.d/proxygateway stop
type:script
message:Stopping Proxy Gateway

[restart]
command:/usr/local/etc/rc.d/proxygateway restart
type:script
message:Restarting Proxy Gateway

[status]
command:/usr/local/opnsense/scripts/OPNsense/ProxyGateway/status.py
type:script_output
message:Proxy Gateway status

[setup]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/ProxyGateway/setup.sh
parameters:%s
type:script
message:Setting up proxy gateway connection %s

[teardown]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/ProxyGateway/teardown.sh
parameters:%s
type:script
message:Tearing down proxy gateway connection %s

[reconfigure]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/ProxyGateway/reconfigure.sh
type:script
message:Reconfiguring Proxy Gateway connections

[healthcheck]
command:/bin/sh /usr/local/opnsense/scripts/OPNsense/ProxyGateway/healthcheck.sh
parameters:%s
type:script_output
message:Health checking proxy gateway %s
